packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@compodoc/compodoc': true
  '@prisma/engines': false
  bcrypt: true
  esbuild: true
  prisma: false
minimumReleaseAgeExclude:
  - lucide-react@1.22.0
  - postcss@8.5.16
